### PR TITLE
ssh agent fixes

### PR DESCRIPTION
**Pull request by waleedhammam**
Resolves: 
- https://github.com/threefoldtech/jumpscaleX/issues/267
- https://github.com/threefoldtech/jumpscaleX/issues/469

## Description
- Fixed redundant calls of ssh-add and similar stuff caused by check function.
- Fixed broken socket or inactive ssh-agent.
- Fixed kosmos start with different ssh-key than id_rsa

**Summary of the changes.**
- Fixed `check` method, which had redundant unnecessary calls that affected performance

**Scenarios**
- ssh-agent is active, socket is available, 1 key loaded:
         .. Loads the key, continue normally using it to encrypt/decrypt private key
- ssh-agent is not active or socket is broken, no key loaded: 
         .. Starts ssh-agent with a new socket, then loads the default key (id_rsa)
- ssh-agent is active, socket is available, no key loaded:
          .. Will load the default key in (id_rsa)

### CODE REVIEW

**Comment by abom** [comment]
@waleedhammam can you please merge development into this and resolve the conflicts?

**Comment by waleedhammam** [comment]
@abom  conflicts fixed. waiting for review

**Comment by 0xIslamTaha** [comment]
@waleedhammam 
**Verification step**
- start jsx docker 
```bash
source /sandbox/env.sh
eval `ssh-agent`
ssh-add
kosmos
```
```python
client_id = ***
client_secret = ***
iyo_instance='random_10'
iyo_client = j.clients.itsyouonline.get(iyo_instance, application_id=client_id, secret=client_secret) 
jwt = iyo_client.jwt_get().jwt
iyo_client.save()
```

Then I rester the container and tried to retrieve the iyo_client again, but I couldnt

image

**Comment by waleedhammam** [comment]
@0xIslamTaha I think the problem is with itsyouonline client.
tested with zos, works ok, after restarting docker
steps:
```
j.clients.zos.get(name="mycl", host="10.102.136.183").save() 
cl = j.clients.zos.get(name="mycl", host="10.102.136.183")
cl
```

**Comment by 0xIslamTaha** [comment]
seems there is a blocker issue here 
https://github.com/threefoldtech/jumpscaleX/issues/551

**Review by rkhamis — APPROVED** [review]

**Pull request merged**
