### PR TITLE
docs(git flow): versioning, branching and commit convention

### PR DESCRIPTION
**Pull request by zgorizzo69**
## Description

Describe how to
- version
- branch
- commit
on threefold repositories

### CODE REVIEW

**Comment by rkhamis** [comment]
While I genuinely love the git flow, this is not the flow we agreed upon with @despiegk. Due to the contributing team size, we found it best to have:

- `master` branch that always has the latest stable release
- `development` branch which has cutting edge development. which can be unstable and does not require PRs
- `development_<feature>` in case a feature branch is needed, specifically to discuss approaches more than for its development. Or, more likely, when destructive changes are being made that will block other developers until stable

So our entire development process is collaborative on one development branch, more or less

**Review by rkhamis — CHANGES_REQUESTED** [review]
See my [comment](https://github.com/threefoldtech/jumpscaleX/pull/485#issuecomment-492605777)

**Comment by zgorizzo69** [comment]
@rkhamis thansk for your comment !
Sorry for all following questions as I am new to the project I need to understand better the flow you describe
- can you elaborate more on the statement 'due to the contributing team size'. What problems do you face with a lot of contributions ? For large open source project the [forking flow ](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow) is preferred but it requires a  code maintainer role. Also it doesn't encourage direct collaboration and "pair" programming as the code maintainer often doesn't have the time to go through detail comments on why the PR is refused  
- does it mean that master is protected and requires PR ?
- as development is not stable from where do you start a new feature branch ? If it is from master then it is difficult for a lot of people to work on the latest development. For instance let's says in prod we have V1.0 and in development everybody is working on V1.1 and it is not stable meaning doesn't build or crash. if I want to add a new feature on V1.1 should I add it on V1.0 and perhaps missing some improvements/ refactoring that has already be done on V1.1 ?
- If someone push a bad commit how do you recover ? ensure that doesn't happen ?
- What are your flow concerning hotfixes ?
- what are your flow to maintain consistency between the different branches ? For instance I can see that my updates on install.md has been merged into development-bcdb but not in development. Are you planning to merge developement-bcdb into developement and then development into master ? Do you have a list of feature to include into development-bcdb before doing that ?
- What about the versioning ? How do you now what version is in production ? the features that it contains ? How do you do rollback ?

If I understand well you may be concern by the complexity of the git flow maybe 
to lighten the flow we could abandon the release branches and merge development into master whenever it make sense and tag it on master.

**Comment by rkhamis** [comment]
@zgorizzo69 It's great that you're asking this, it's always good to rethink the current process....

For a start, this is how we work: https://github.com/threefoldtech/home/blob/master/docs/development_process.md


The problem with the git flow with us is that it's too restricting to our level of agility. It slows us down a little too much by being such a rigid process. Instead, we always believe that each contributor in the team feels the responsibility and the ownership and the foresight to be trusted to commit to the same development branch. It makes all changes available all the time and prevents sometimes painful merges.

Only when a feature requires a lot of discussion regarding approach/the developer(s) are unsure of its reception into the codebase do they create a separate branch for it. They branch off from `development` and make sure their branch stays rebased constantly. They also try to merge back as soon as possible.
Same goes obviously for any destructive changes that would block other developers.

Development branch should be unstable but installable for sure. It should only have a small degree of unstability or incompleteness that should never block any other developer on that branch.

Master is indeed protected and only merged into with a release. That means it's always latest released version. we always release with a tag for deployments running older versions.

Hotfixes are done on a short-living branch where they're merged into development and master and retagged (re-released)

I think I answered everything up there except for the development-bcdb branch... this is a destructive change so it's an example of what I was discussing before. Your changes should've been merged to development rather than there, but it's the same concept.

Please let me know if you have any more questions!

**Comment by rkhamis** [comment]
@zgorizzo69 I'll close this PR since it does not conform to our current development process.

**Comment by zaibon** [comment]
@rkhamis maybe we can reformulate the content, cause I think this document is still pretty nice. With the git example and stuff. Nice to have for new contributors

**Comment by rkhamis** [comment]
@zaibon that's why I left the branch

**Comment by zgorizzo69** [comment]
@zaibon sure and to have a convention for commit can be nice also maybe something way simpler but still it will then be easy to populate the changelog

**Pull request closed without merging**
